# Generated by Django 5.1.7 on 2025-06-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampapers', '0004_paper_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='uploads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_uploads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
