# Generated by Django 5.1.7 on 2025-06-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exampapers",
            "0006_payment_status_alter_order_status_alter_order_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
