# Generated by Django 5.1.7 on 2025-06-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exampapers", "0007_alter_order_status_delete_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paper",
        ),
        migrations.AddField(
            model_name="order",
            name="papers",
            field=models.ManyToManyField(to="exampapers.paper"),
        ),
    ]
