# Generated by Django 5.1.7 on 2025-06-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exampapers", "0008_remove_order_paper_order_papers"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="preview_file",
            field=models.FileField(blank=True, null=True, upload_to="previews/"),
        ),
    ]
