# Generated by Django 5.1.7 on 2025-07-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exampapers", "0010_paperdownload"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="credited",
            field=models.BooleanField(default=False),
        ),
    ]
