# Generated by Django 5.1.7 on 2025-07-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exampapers", "0011_order_credited"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
