# Generated by Django 5.1.7 on 2025-07-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exampapers",
            "0013_course_category_course_created_at_course_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="year",
            field=models.CharField(
                blank=True,
                help_text="Academic year format: YYYY/YYYY (e.g., 2023/2024)",
                max_length=9,
                null=True,
            ),
        ),
    ]
