# Generated by Django 5.1.7 on 2025-07-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exampapers", "0015_paper_preview_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
        migrations.RemoveField(
            model_name="course",
            name="schools",
        ),
    ]
