# Generated by Django 5.1.7 on 2025-07-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_organizationaccount_userpayoutprofile_wallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="last_withdrawal_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
