# Generated by Django 5.1.7 on 2025-07-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_wallet_currency_wallet_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayoutprofile",
            name="preferred_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("mpesa", "M-Pesa"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
