# Generated by Django 5.1.7 on 2025-07-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_userpayoutprofile_preferred_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpayoutprofile",
            name="preferred_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("mpesa", "M-Pesa"),
                    ("Paystack", "Paystack"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="method",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("mpesa", "M-Pesa"),
                    ("Paystack", "Paystack"),
                ],
                max_length=20,
            ),
        ),
    ]
