# Generated by Django 5.1.7 on 2025-08-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_userpayoutprofile_preferred_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpayoutprofile",
            name="preferred_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("mpesa", "M-Pesa"),
                    ("Paystack", "Paystack"),
                    ("pesapal", "PesaPal"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
