# Generated by Django 5.1.7 on 2025-08-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_alter_userpayoutprofile_preferred_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("mpesa", "Mpesa"),
                    ("paystack", "Paystack"),
                    ("pesapal", "PesaPal"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="method",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("mpesa", "M-Pesa"),
                    ("Paystack", "Paystack"),
                    ("pesapal", "PesaPal"),
                ],
                max_length=20,
            ),
        ),
    ]
