# Generated by Django 5.1.7 on 2025-10-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_alter_payment_gateway_alter_withdrawalrequest_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("mpesa", "Mpesa"),
                    ("paystack", "Paystack"),
                    ("pesapal", "PesaPal"),
                    ("intasend", "Intasend"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userpayoutprofile",
            name="preferred_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("mpesa", "M-Pesa"),
                    ("Paystack", "Paystack"),
                    ("pesapal", "PesaPal"),
                    ("intasend", "Intasend"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="method",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("mpesa", "M-Pesa"),
                    ("Paystack", "Paystack"),
                    ("pesapal", "PesaPal"),
                    ("intasend", "Intasend"),
                ],
                max_length=20,
            ),
        ),
    ]
