# Generated by Django 5.1.7 on 2025-07-28 06:45

import re

from django.db import migrations


def generate_username(first_name, last_name, email):
    # Combine names or use email
    if first_name and last_name:
        base = f"{first_name}_{last_name}".lower()
    else:
        base = email.split("@")[0]

    # Clean the username
    base = re.sub(r"[^\w]", "", base)
    return base


def populate_usernames(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if not user.username:  # Only set if empty
            username = generate_username(user.first_name, user.last_name, user.email)

            # Ensure uniqueness
            counter = 1
            while User.objects.filter(username=username).exists():
                username = f"{username}_{counter}"
                counter += 1

            user.username = username
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_user_username_alter_user_groups_alter_user_is_active"),
    ]

    operations = [
        migrations.RunPython(populate_usernames),
    ]
