# Generated by Django 5.1.7 on 2025-07-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active."
                "Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
