# Generated by Django 5.1.7 on 2025-08-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active."
                "Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
