# Generated by Django 5.1.7 on 2025-06-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("payment_intent", models.CharField(max_length=100)),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("charge_id", models.CharField(blank=True, max_length=100, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_payment",
                        to="payments.payment",
                    ),
                ),
            ],
        ),
    ]
