# Generated by Django 5.1.7 on 2025-05-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0002_mpesapayment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='organization_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
