# Generated by Django 5.1.7 on 2025-07-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0007_alter_userpayoutprofile_preferred_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaystackPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("access_code", models.CharField(max_length=100)),
                ("authorization_url", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paystack_payment",
                        to="payments.payment",
                    ),
                ),
            ],
        ),
    ]
