# Generated by Django 5.1.7 on 2025-10-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0010_alter_payment_gateway_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntaSendPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_id", models.CharField(max_length=100, unique=True)),
                ("checkout_url", models.URLField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intasend_payment",
                        to="payments.payment",
                    ),
                ),
            ],
        ),
    ]
