# Generated by Django 5.1.7 on 2025-06-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paypal_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paypalpayment",
            options={},
        ),
        migrations.RemoveField(
            model_name="paypalpayment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="paypalpayment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="paypalpayment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="paypalpayment",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="paypalpayment",
            name="paypal_order_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
