# Generated by Django 5.1.7 on 2025-06-15 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_order_paymentevent"),
        ("paypal_api", "0002_alter_paypalpayment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paypalpayment",
            options={
                "verbose_name": "PayPal Payment",
                "verbose_name_plural": "PayPal Payments",
            },
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="capture_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="payer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="payer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="payment",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paypal_payment",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("approved", "Approved"),
                    ("captured", "Captured"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
