# Generated by Django 5.1.7 on 2025-08-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "exampapers",
            "0016_remove_course_category_remove_course_description_and_more",
        ),
        ("payments", "0009_alter_payment_gateway_alter_withdrawalrequest_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="PesapalPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_id", models.CharField(max_length=255, unique=True)),
                ("merchant_reference", models.CharField(max_length=255, unique=True)),
                ("ipn_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("raw_callback_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesapal_payments",
                        to="exampapers.order",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesapal_payment",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pesapal Payment",
                "verbose_name_plural": "Pesapal Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
